### ISSUE TITLE
a question on portability

### ISSUE THREAD

**Issue by Tcll** [pyglfw/pyglfw#1]
I've installed this once, but my wine prefix decided to corrupt it before I could test it.

I've installed portable python 2.7.6.1, specifically for PyOpenGL, and am wondering if pyglfw would need any additional downloads??

for example, PyOpenGL expects to use the native OpenGL libraries on the machine,
but I've ported the 3rd-party official libraries into PyOpenGL and made sure ctypes skipped system32 and sysWOW64 access.

would I need to do the same to this??

**Comment by RomanValov** [comment]
Actually pyglfw is just a wrapper around glfw library. So you need glfw3.dll in order to get pyglfw working. Look http://www.glfw.org/download.html for the binaries with respect to your python interpreter arch, i.e. 32-bit libraries should be used in pair with 32-bit python installation. Dll should be put either in system-wide dir (like system32) or in your project dir. Once you put library file in proper place you'll get `import pyglfw.pyglfw` executes without exceptions.

As of PyOpenGL. Strictly speaking those libs aren't required for pyglfw to function properly (i.e. window management and input handling will work). However you still need OpenGL if you want to render something and usually you will :)

**Comment by Tcll** [comment]
woops I think I mis-stated myself there with the PyOpenGL thing.
I meant that towards me using Python27 and not Python3.

anyways, thanks for the information :)

I'll close this issue when I get it working,
else I'll forward info on any external requirements. ;)

**Comment by Tcll** [comment]
All I did was copy pyglfw from the zip to the local directory, included glfw3.dll and OpenGL/, and the windows.py example worked right out of the box. =D

Very nice job man!
This makes a fine replacement for pygame ^_^
(I'm sick of the SDL bug deleting my GL context on window resize)

**Comment by xiconxi** [comment]
> Actually pyglfw is just a wrapper around glfw library. So you need glfw3.dll in order to get pyglfw working. Look http://www.glfw.org/download.html for the binaries with respect to your python interpreter arch, i.e. 32-bit libraries should be used in pair with 32-bit python installation. Dll should be put either in system-wide dir (like system32) or in your project dir. Once you put library file in proper place you'll get `import pyglfw.pyglfw` executes without exceptions.
> 
> As of PyOpenGL. Strictly speaking those libs aren't required for pyglfw to function properly (i.e. window management and input handling will work). However you still need OpenGL if you want to render something and usually you will :)

In MacOS, glfw3 was installed by ` brew install glfw3', it's packge name is glfw 3.2.1 rather than glfw3 *.*.*. So I suggest make some adaptation, or just replace 'libglfw3.dylib' in pyglfw/libapi/function.py with 'libglfw.dylib'
